### ISSUE TITLE
Crash trying to initialize screen coordinates

### ISSUE THREAD

**Issue by wonder99** [rowengb/GSPro-MLM2PRO-OCR#3]
- Press enter after you've hit your first shot. -
←[91mMLM2PRO Connector ||←[0m Tesseract API ended...
Traceback (most recent call last):
  File "connector.py", line 79, in main
  File "socket_connection.py", line 6, in create_socket_connection
    sock.connect(server_address)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "connector.py", line 200, in main
TypeError: print_colored_prefix() takes 3 positional arguments but 4 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "connector.py", line 211, in <module>
  File "connector.py", line 206, in main
UnboundLocalError: cannot access local variable 'sock' where it is not associated with a value
[19112] Failed to execute script 'connector' due to unhandled exception!

**Comment by wonder99** [comment]
I think this was due to GSPRO not running at the time.  Closing
